import { Bellefair, Barlow_Condensed } from "next/font/google";

import "./globals.css";
import Header from "./components/Header";

const bellefair = Bellefair({
  variable:"--font-bellefair",
  subsets:["latin"],
  weight:'400'
})
const barlow = Barlow_Condensed({
  variable:"--font-barlow",
  subsets:["latin"],
  weight:['100','200','300','400','500','600']
})
export const metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-cover bg-no-repeat bg-center min-h-screen grid grid-rows-[auto_1fr]"
      >
        <Header/>
        <main className="container lg:max-w-[1110px] md:max-w-[688px] h-full m-auto ">
          {children}
        </main>
      </body>
    </html>
  );
}
